version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7071:3000"
    volumes:
      - /app/node_modules
      - .:/app #Want to map the current folder to the app folder inside the container
  tests:
    build: .
    volumes:
      - /app/node_modules
      - .:/app #Want to map the current folder to the app folder inside the container
    command: ["npm","run","test"]
